export const CHARACTER_STORAGE_KEY = 'skyBlaster.selectedCharacterId';
export const PROFILE_STORAGE_KEY = 'skyBlaster.profile.v2';
export const WORLDS_COUNT = 4;
export const LEVELS_PER_WORLD = 5;
export const WAVES_PER_LEVEL = 10;
export const WAVE_INTERVAL_SECONDS = 30;

export const CHARACTER_DEFS = [
  {
    id: 'char_01',
    name: 'Vanguard',
    roleLabel: 'Frontline Rifleman',
    weaponLabel: 'MX-5 Rifle',
    playstyleLabel: 'Ausgewogen · präzise Einzelschüsse',
    tagline: 'Balanced assault frame with disciplined rifle pressure and dependable pacing.',
    classSummary: 'Der Allrounder für konstante Midrange-DPS, sauberes Zielen und kontrollierte Rotationen.',
    traitTags: ['Balanced', 'Reliable', 'Midrange'],
    uiStats: { mobility: 3, power: 3, control: 3 },
    base: 0x66e8ff,
    dark: 0x163a5a,
    accent: 0xd6fbff,
    emissive: 0x0b2e47,
    trim: 0xf3ffff,
    bodyScale: [1.02, 1.12, 0.96],
    head: 'visor',
    shoulderPads: true,
    legType: 'balanced',
    silhouette: 'vanguard',
    weapon: 'rifle',
    combatProfile: {
      weaponType: 'rifle',
      weaponTag: 'rifle',
      statusApplicationMode: 'precision',
      reactionBias: 1.18,
      aoeBias: 0.82,
      chainBias: 1.08,
      dotBias: 0.94,
      burstBias: 1.16,
      precisionBias: 1.22,
      weaponProfile: {
        shotPattern: 'single',
        patternProjectiles: 1,
        spread: 0.012,
        burstCount: 1,
        burstInterval: 0,
        pierce: 0,
        projectileScale: 1,
        projectileSpeedModifier: 1,
        projectileLifeMultiplier: 1.02,
        projectileGeometry: 'pulse',
        projectileSpin: 0,
        muzzleForward: 1.18,
        muzzleHeight: 1.34,
        muzzleWidth: 0.1,
      },
      baseMoveSpeedModifier: 1,
      baseDamageModifier: 1,
      baseAttackCooldown: 0.18,
      fireRateModifier: 1,
    },
    locomotionProfile: {
      acceleration: 14,
      deceleration: 16,
      animationProfile: 'balanced',
      runCycleSpeed: 11,
      bounce: 0.11,
      bodyLean: 0.18,
      armSwing: 0.56,
      legSwing: 0.92,
      idleSway: 0.035,
      weaponSway: 0.015,
    },
  },
  {
    id: 'char_02',
    name: 'Scout',
    roleLabel: 'Scout Skirmisher',
    weaponLabel: 'Lynx Carbine',
    playstyleLabel: 'Burst-Scout · hohe Mobilität',
    tagline: 'Long-legged recon frame that snaps out tight burst strings while dancing through lanes.',
    classSummary: 'Hohe Mobilität, schnelle Zielwechsel und 3er-Bursts für kontrollierten Hit-and-run-Druck.',
    traitTags: ['Scout', 'Burst', 'Fast'],
    uiStats: { mobility: 5, power: 2, control: 4 },
    base: 0x8df07c,
    dark: 0x1f4f2f,
    accent: 0xe7ffd9,
    emissive: 0x1b3b16,
    trim: 0xf6ffe8,
    bodyScale: [0.9, 1.02, 1.18],
    head: 'antenna',
    shoulderPads: false,
    legType: 'long',
    silhouette: 'strider',
    weapon: 'carbine',
    combatProfile: {
      weaponType: 'burstCarbine',
      weaponTag: 'carbine',
      statusApplicationMode: 'burst',
      reactionBias: 1.08,
      aoeBias: 0.92,
      chainBias: 1.1,
      dotBias: 0.98,
      burstBias: 1.04,
      precisionBias: 1.12,
      weaponProfile: {
        shotPattern: 'single',
        patternProjectiles: 1,
        spread: 0.026,
        burstCount: 3,
        burstInterval: 0.052,
        pierce: 0,
        projectileScale: 0.9,
        projectileSpeedModifier: 1.22,
        projectileLifeMultiplier: 1.08,
        projectileGeometry: 'dart',
        projectileSpin: 12,
        muzzleForward: 1.24,
        muzzleHeight: 1.38,
        muzzleWidth: 0.06,
      },
      baseMoveSpeedModifier: 1.14,
      baseDamageModifier: 0.78,
      baseAttackCooldown: 0.28,
      fireRateModifier: 1,
    },
    locomotionProfile: {
      acceleration: 22,
      deceleration: 20,
      animationProfile: 'scout',
      runCycleSpeed: 14.5,
      bounce: 0.15,
      bodyLean: 0.24,
      armSwing: 0.64,
      legSwing: 1.16,
      idleSway: 0.05,
      weaponSway: 0.028,
    },
  },
  {
    id: 'char_03',
    name: 'Bulwark',
    roleLabel: 'Siege Tank',
    weaponLabel: 'Bastion Cannon',
    playstyleLabel: 'Langsam · schwer · hoher Alpha-Schaden',
    tagline: 'Heavy armor shell that lobs crushing cannon slugs with built-in penetration.',
    classSummary: 'Der Tank: langsam, massiv und mit durchschlagenden schweren Schüssen für Frontdruck.',
    traitTags: ['Tank', 'Pierce', 'Heavy'],
    uiStats: { mobility: 1, power: 5, control: 3 },
    base: 0xffba66,
    dark: 0x6f3a19,
    accent: 0xffeed2,
    emissive: 0x51270d,
    trim: 0xfff6e6,
    bodyScale: [1.22, 1.28, 0.92],
    head: 'heavy',
    shoulderPads: true,
    legType: 'heavy',
    silhouette: 'bulwark',
    weapon: 'cannon',
    combatProfile: {
      weaponType: 'heavyCannon',
      weaponTag: 'cannon',
      statusApplicationMode: 'impact',
      reactionBias: 0.88,
      aoeBias: 1.34,
      chainBias: 0.84,
      dotBias: 0.9,
      burstBias: 1.3,
      precisionBias: 0.86,
      weaponProfile: {
        shotPattern: 'single',
        patternProjectiles: 1,
        spread: 0.02,
        burstCount: 1,
        burstInterval: 0,
        pierce: 2,
        projectileScale: 1.42,
        projectileSpeedModifier: 0.82,
        projectileLifeMultiplier: 1.14,
        projectileGeometry: 'slug',
        projectileSpin: 4.5,
        muzzleForward: 1.26,
        muzzleHeight: 1.42,
        muzzleWidth: 0.14,
        hitRadius: 0.28,
      },
      baseMoveSpeedModifier: 0.84,
      baseDamageModifier: 1.95,
      baseAttackCooldown: 0.42,
      fireRateModifier: 1,
    },
    locomotionProfile: {
      acceleration: 8,
      deceleration: 11,
      animationProfile: 'tank',
      runCycleSpeed: 8.2,
      bounce: 0.06,
      bodyLean: 0.12,
      armSwing: 0.34,
      legSwing: 0.56,
      idleSway: 0.022,
      weaponSway: 0.008,
    },
  },
  {
    id: 'char_04',
    name: 'Sentinel',
    roleLabel: 'Sentinel Controller',
    weaponLabel: 'Arc Bladegun',
    playstyleLabel: 'Kontrolle · Fan-Volley · Raum sichern',
    tagline: 'Ceremonial sentinel that fans blade-bolts in a disciplined arc to lock down space.',
    classSummary: 'Kontrolliert Zonen mit breitem Fan-Spread, stabiler Bewegung und guter Flächenabdeckung.',
    traitTags: ['Sentinel', 'Fan Volley', 'Control'],
    uiStats: { mobility: 3, power: 3, control: 5 },
    base: 0xc698ff,
    dark: 0x422563,
    accent: 0xf4ebff,
    emissive: 0x2f174a,
    trim: 0xfcf6ff,
    bodyScale: [1.04, 1.02, 0.88],
    head: 'crest',
    shoulderPads: false,
    legType: 'angled',
    silhouette: 'warden',
    weapon: 'bladegun',
    combatProfile: {
      weaponType: 'arcBladegun',
      weaponTag: 'bladegun',
      statusApplicationMode: 'fan',
      reactionBias: 1,
      aoeBias: 1.16,
      chainBias: 1.02,
      dotBias: 1,
      burstBias: 0.96,
      precisionBias: 0.94,
      weaponProfile: {
        shotPattern: 'fan',
        patternProjectiles: 3,
        spread: 0.2,
        burstCount: 1,
        burstInterval: 0,
        pierce: 1,
        projectileScale: 1.02,
        projectileSpeedModifier: 0.95,
        projectileLifeMultiplier: 1.08,
        projectileGeometry: 'blade',
        projectileSpin: 15,
        muzzleForward: 1.16,
        muzzleHeight: 1.37,
        muzzleWidth: 0.18,
        hitRadius: 0.22,
      },
      baseMoveSpeedModifier: 0.96,
      baseDamageModifier: 0.72,
      baseAttackCooldown: 0.24,
      fireRateModifier: 1,
    },
    locomotionProfile: {
      acceleration: 12,
      deceleration: 14,
      animationProfile: 'sentinel',
      runCycleSpeed: 9.4,
      bounce: 0.085,
      bodyLean: 0.16,
      armSwing: 0.42,
      legSwing: 0.72,
      idleSway: 0.03,
      weaponSway: 0.018,
    },
  },
  {
    id: 'char_05',
    name: 'Rogue',
    roleLabel: 'Flanker Duelist',
    weaponLabel: 'Shade SMGs',
    playstyleLabel: 'Doppel-SMG · hohe Feuerrate',
    tagline: 'Compact flanker chassis tuned for relentless dual-weapon pressure and sharp angle changes.',
    classSummary: 'Aggressiver Flanker mit Doppel-SMG-Salve, sehr hoher Kadenz und schneller Richtungswechsel-Response.',
    traitTags: ['Flank', 'Dual', 'Rapid'],
    uiStats: { mobility: 4, power: 2, control: 2 },
    base: 0xff86ac,
    dark: 0x62223b,
    accent: 0xffe2ee,
    emissive: 0x4d1527,
    trim: 0xfff0f5,
    bodyScale: [0.84, 1.01, 1.06],
    head: 'split',
    shoulderPads: true,
    legType: 'runner',
    silhouette: 'rogue',
    weapon: 'smg',
    combatProfile: {
      weaponType: 'dualSmg',
      weaponTag: 'smg',
      statusApplicationMode: 'rapid',
      reactionBias: 0.92,
      aoeBias: 0.9,
      chainBias: 0.96,
      dotBias: 1.24,
      burstBias: 0.88,
      precisionBias: 0.82,
      weaponProfile: {
        shotPattern: 'dual',
        patternProjectiles: 2,
        spread: 0.06,
        burstCount: 1,
        burstInterval: 0,
        pierce: 0,
        projectileScale: 0.74,
        projectileSpeedModifier: 1.04,
        projectileLifeMultiplier: 0.96,
        projectileGeometry: 'needle',
        projectileSpin: 18,
        muzzleForward: 1.08,
        muzzleHeight: 1.31,
        muzzleWidth: 0.34,
      },
      baseMoveSpeedModifier: 1.08,
      baseDamageModifier: 0.46,
      baseAttackCooldown: 0.11,
      fireRateModifier: 1,
    },
    locomotionProfile: {
      acceleration: 20,
      deceleration: 22,
      animationProfile: 'rogue',
      runCycleSpeed: 15.2,
      bounce: 0.13,
      bodyLean: 0.28,
      armSwing: 0.72,
      legSwing: 1.04,
      idleSway: 0.042,
      weaponSway: 0.024,
    },
  },
];

export const UPGRADE_DEFS = [
  { id: 'baseDamage', group: 'Pilot Upgrades', label: 'Base Damage', description: 'Erhöht den Schaden jeder Kugel.', baseCost: 60, costStep: 35, maxLevel: 12, format: (lvl) => `${(1 + lvl * 0.22).toFixed(2)}x` },
  { id: 'attackSpeed', group: 'Pilot Upgrades', label: 'Attack Speed', description: 'Senkt das Feuerintervall deines Blasters.', baseCost: 70, costStep: 40, maxLevel: 10, format: (lvl) => `${Math.max(0.07, 0.18 * Math.pow(0.94, lvl)).toFixed(2)}s` },
  { id: 'maxHealth', group: 'Pilot Upgrades', label: 'Max Health', description: 'Mehr Lebenspunkte pro Run.', baseCost: 80, costStep: 45, maxLevel: 12, format: (lvl) => `${100 + lvl * 14} HP` },
  { id: 'movementSpeed', group: 'Pilot Upgrades', label: 'Movement Speed', description: 'Schnelleres Traversieren der Arena.', baseCost: 55, costStep: 30, maxLevel: 12, format: (lvl) => `${(1 + lvl * 0.05).toFixed(2)}x` },
  { id: 'upgradeLimit', group: 'Pilot Upgrades', label: 'Upgrade Limit', description: 'Erhöht das Limit aller anderen Upgrades dauerhaft um 1. Dieses Upgrade hat selbst kein Limit.', baseCost: 140, costStep: 90, format: (lvl) => `+${lvl} Level auf andere Upgrades` },
  { id: 'burnDamage', group: 'Power-up Upgrades', label: 'Burn Damage', description: 'Verstärkt Feuer-DOT.', baseCost: 65, costStep: 36, maxLevel: 10, format: (lvl) => `${(1 + lvl * 0.18).toFixed(2)}x` },
  { id: 'poisonDamage', group: 'Power-up Upgrades', label: 'Poison Damage', description: 'Verstärkt Gift-DOT.', baseCost: 65, costStep: 36, maxLevel: 10, format: (lvl) => `${(1 + lvl * 0.18).toFixed(2)}x` },
  { id: 'slowDuration', group: 'Power-up Upgrades', label: 'Slow Duration', description: 'Verlängert die Wirkzeit von Ice.', baseCost: 60, costStep: 34, maxLevel: 10, format: (lvl) => `${(1.2 + lvl * 0.16).toFixed(1)}s` },
  { id: 'lightningRange', group: 'Power-up Upgrades', label: 'Lightning Range', description: 'Längere Kettenreichweite für Blitz-Treffer.', baseCost: 72, costStep: 42, maxLevel: 10, format: (lvl) => `${(6.5 + lvl * 0.45).toFixed(1)}m` },
  { id: 'rocketRadius', group: 'Power-up Upgrades', label: 'Rocket Radius', description: 'Größere Explosionsradien.', baseCost: 72, costStep: 42, maxLevel: 10, format: (lvl) => `${(1.8 + lvl * 0.18).toFixed(1)}m` },
  { id: 'shieldCapacity', group: 'Power-up Upgrades', label: 'Shield Capacity', description: 'Shields absorbieren mehr Schaden.', baseCost: 68, costStep: 38, maxLevel: 10, format: (lvl) => `${26 + lvl * 6} HP` },
];

export const STAT_DEFS = [
  { id: 'totalKills', label: 'Total kills', format: (v) => String(v) },
  { id: 'totalRuns', label: 'Total runs', format: (v) => String(v) },
  { id: 'highestWaveReached', label: 'Highest wave reached', format: (v) => String(v) },
  { id: 'damageDealt', label: 'Damage dealt', format: (v) => String(Math.round(v)) },
  { id: 'timePlayed', label: 'Time played', format: (v) => formatDuration(v) },
  { id: 'powerUpsCollected', label: 'Power-ups collected', format: (v) => String(v) },
  { id: 'bossesDefeated', label: 'Bosses defeated', format: (v) => String(v) },
];

export const gameplayConfig = {
  controls: {
    rotationDeadZone: 0.32,
    moveStartRadius: 0.38,
    fineMoveRadius: 0.56,
    highSpeedRadius: 0.88,
    maxInputRadius: 44,
    speedExponent: 1.8,
    minMoveSpeed: 1.4,
    maxMoveSpeed: 10.8,
  },
  camera: {
    fov: 64,
    height: 39,
    forwardOffset: 0.001,
    lookAtHeight: 0.2,
  },
  arena: {
    size: 112,
    gridDivisions: 36,
    padding: 3,
    spawnMinDistance: 24,
    spawnMaxDistance: 46,
  },
  pickups: {
    collisionRadius: 0.62,
  },
  enemies: {
    waveSpeedScale: {
      field: 0.06,
      boss: 0.04,
    },
    randomVariance: 0.08,
    baseSpeedMultiplier: {
      runner: 1,
      tank: 1,
      shooter: 1,
      swarm: 0.95,
      charger: 1,
      splitter: 1,
      bossHeavy: 1,
      bossAgile: 1,
      earthTitan: 1,
    },
  },
};

export const POWER_UP_DEFS = {
  fire: { kind: 'projectile', label: 'Fire', color: 0xff7f4d, icon: '🔥', symbol: 'FR', shortLabel: 'Burn' },
  ice: { kind: 'projectile', label: 'Ice', color: 0x8de0ff, icon: '❄️', symbol: 'IC', shortLabel: 'Freeze' },
  lightning: { kind: 'projectile', label: 'Lightning', color: 0x95a8ff, icon: '⚡', symbol: 'LT', shortLabel: 'Shock' },
  poison: { kind: 'projectile', label: 'Poison', color: 0x7bdf64, icon: '☠️', symbol: 'PX', shortLabel: 'Toxin' },
  rockets: { kind: 'projectile', label: 'Rockets', color: 0xffa34a, icon: '🚀', symbol: 'RK', shortLabel: 'Blast' },
  doubler: { kind: 'projectile', label: 'Doubler', color: 0xfff38c, icon: '✖️', symbol: 'DB', shortLabel: 'Multi' },
  health: { kind: 'player', label: 'Health', color: 0xff8faf, icon: '❤️', symbol: 'HP', shortLabel: 'Repair' },
  movementSpeed: { kind: 'player', label: 'Move Speed', color: 0x66ffd8, icon: '🏃', symbol: 'MV', shortLabel: 'Rush' },
  shield: { kind: 'player', label: 'Shield', color: 0x79d7ff, icon: '🛡️', symbol: 'SH', shortLabel: 'Aegis' },
};



export const POWER_STACK_THRESHOLDS = {
  fire: {
    threshold_1: { stacks: 2, unlocks: ['synergy:thermal_conductor'], hudLabel: 'Fire II · Thermoleitung' },
    threshold_2: { stacks: 4, flags: { fireCatalyst: true }, hudLabel: 'Fire IV · Brandbeschleuniger' },
    threshold_3: { stacks: 6, flags: { infernoPulse: true }, hudLabel: 'Fire VI · Inferno-Puls' },
  },
  ice: {
    threshold_1: { stacks: 2, unlocks: ['synergy:cryo_venom'], hudLabel: 'Ice II · Kryo-Gift' },
    threshold_2: { stacks: 4, flags: { shatterPrep: true }, hudLabel: 'Ice IV · Splitterfrost' },
    threshold_3: { stacks: 6, unlocks: ['synergy:frostfire_rupture'], hudLabel: 'Ice VI · Frostbrand' },
  },
  lightning: {
    threshold_1: { stacks: 2, unlocks: ['synergy:thermal_conductor'], hudLabel: 'Lightning II · Leitbogen' },
    threshold_2: { stacks: 4, flags: { chainOverload: true }, hudLabel: 'Lightning IV · Kettenüberladung' },
    threshold_3: { stacks: 6, flags: { stormEcho: true }, hudLabel: 'Lightning VI · Sturmecho' },
  },
  poison: {
    threshold_1: { stacks: 2, unlocks: ['synergy:cryo_venom'], hudLabel: 'Poison II · Kryotoxin' },
    threshold_2: { stacks: 4, flags: { corrosionSpread: true }, hudLabel: 'Poison IV · Korrosionswolke' },
    threshold_3: { stacks: 6, flags: { plagueCascade: true }, hudLabel: 'Poison VI · Pestkaskade' },
  },
  rockets: {
    threshold_1: { stacks: 2, unlocks: ['synergy:volatile_payload'], hudLabel: 'Rockets II · Volatile Payload' },
    threshold_2: { stacks: 4, flags: { blastPrime: true }, hudLabel: 'Rockets IV · Sprengkopf+' },
    threshold_3: { stacks: 6, flags: { blastTransfer: true }, hudLabel: 'Rockets VI · Nachbrenner' },
  },
  doubler: {
    threshold_1: { stacks: 1, flags: { multiThreaded: true }, hudLabel: 'Doubler I · Reaktionsdichte' },
    threshold_2: { stacks: 2, flags: { multiCascade: true }, hudLabel: 'Doubler II · Split-Reaktion' },
    threshold_3: { stacks: 3, flags: { multiStability: true }, hudLabel: 'Doubler III · Stabiler Schwarm' },
  },
};

export const POWER_SYNERGY_DEFS = {
  thermal_conductor: {
    id: 'thermal_conductor',
    hudLabel: 'Thermal Conductor',
    priority: 90,
    requiredPowers: ['fire', 'lightning'],
    requiredStacks: { fire: 2, lightning: 2 },
    requiredFlags: ['fireCatalyst'],
    triggerType: 'onHit',
    weaponTags: ['rifle', 'carbine', 'bladegun', 'smg', 'cannon'],
    effectConfig: {
      requiresTargetStatuses: ['fireDot'],
      bonusDamage: 2.5,
      bonusDamagePerStack: 0.42,
      statusAmplify: { shockTimer: 0.28, fireDot: 0.18 },
      consumeStatuses: { fireDot: 0.2 },
      cooldownFrames: 5,
      maxChainDepth: 1,
      reactionVfx: 'lightning',
    },
  },
  cryo_venom: {
    id: 'cryo_venom',
    hudLabel: 'Cryo Venom',
    priority: 80,
    requiredPowers: ['ice', 'poison'],
    requiredStacks: { ice: 2, poison: 2 },
    triggerType: 'onStatusApply',
    weaponTags: ['rifle', 'carbine', 'bladegun', 'smg', 'cannon'],
    effectConfig: {
      requiresTargetStatuses: ['poisonDot', 'iceSlowTimer'],
      bonusDamage: 1.8,
      bonusDamagePerStack: 0.3,
      statusAmplify: { poisonDot: 0.4, iceSlowTimer: 0.22 },
      addPrimedEffect: 'cryo_venom',
      reactionVfx: 'poison',
    },
  },
  frostfire_rupture: {
    id: 'frostfire_rupture',
    hudLabel: 'Frostfire Rupture',
    priority: 100,
    requiredPowers: ['fire', 'ice'],
    requiredStacks: { fire: 3, ice: 2 },
    requiredFlags: ['shatterPrep'],
    triggerType: 'onHit',
    weaponTags: ['rifle', 'carbine', 'bladegun', 'smg', 'cannon'],
    effectConfig: {
      requiresTargetStatuses: ['fireDot', 'iceSlowTimer'],
      bonusDamage: 3.6,
      bonusDamagePerStack: 0.52,
      statusAmplify: { fireDot: 0.25, iceSlowTimer: 0.3 },
      consumeStatuses: { iceSlowTimer: 0.35 },
      splashRadius: 2.6,
      splashDamage: 2.2,
      reactionVfx: 'fire',
    },
  },
  volatile_payload: {
    id: 'volatile_payload',
    hudLabel: 'Volatile Payload',
    priority: 70,
    requiredPowers: ['rockets', 'fire'],
    requiredStacks: { rockets: 2, fire: 1 },
    triggerType: 'onExplosion',
    weaponTags: ['rifle', 'carbine', 'bladegun', 'smg', 'cannon'],
    effectConfig: {
      requiresTargetStatuses: ['fireDot'],
      bonusDamage: 2.2,
      bonusDamagePerStack: 0.35,
      splashRadius: 3.4,
      splashDamage: 2.8,
      igniteNearby: 1.4,
      reactionVfx: 'rockets',
    },
  },
  plague_burst: {
    id: 'plague_burst',
    hudLabel: 'Plague Burst',
    priority: 60,
    requiredPowers: ['poison', 'lightning'],
    requiredStacks: { poison: 3, lightning: 2 },
    requiredFlags: ['corrosionSpread'],
    triggerType: 'onKill',
    weaponTags: ['rifle', 'carbine', 'bladegun', 'smg', 'cannon'],
    effectConfig: {
      requiresTargetStatuses: ['poisonDot'],
      radius: 4.4,
      burstDamage: 3.2,
      transferStatus: { poisonDot: 3.2, shockTimer: 0.32 },
      maxTargets: 5,
      reactionVfx: 'poison',
    },
  },
  static_ice_burst: {
    id: 'static_ice_burst',
    hudLabel: 'Static Ice Burst',
    priority: 65,
    requiredPowers: ['ice', 'lightning'],
    requiredStacks: { ice: 3, lightning: 2 },
    requiredFlags: ['chainOverload'],
    triggerType: 'onDeathBurst',
    weaponTags: ['rifle', 'carbine', 'bladegun', 'smg', 'cannon'],
    effectConfig: {
      requiresTargetStatuses: ['iceSlowTimer', 'shockTimer'],
      radius: 4.8,
      burstDamage: 2.6,
      transferStatus: { iceSlowTimer: 0.9, shockTimer: 0.22 },
      maxTargets: 6,
      reactionVfx: 'ice',
    },
  },
};

export const RUN_BASE = {
  moveSpeedMultiplier: 1,
  projectileCount: 1,
};

export const ENEMY_TYPES = {
  runner: { role: 'field', hp: 2, speed: 4.6, damage: 22, radius: 0.72, score: 11 },
  tank: { role: 'field', hp: 8, speed: 1.75, damage: 34, radius: 1.2, score: 16 },
  shooter: { role: 'field', hp: 4, speed: 2.55, damage: 18, radius: 0.92, score: 14, range: 13.5, keepDistance: 8.5, fireRate: 1.4 },
  swarm: { role: 'field', hp: 1, speed: 5.1, damage: 12, radius: 0.42, score: 7 },
  charger: { role: 'field', hp: 5, speed: 2.6, damage: 26, radius: 0.95, score: 15, chargeSpeed: 9.2, chargeCooldown: 2.2, chargeDuration: 0.45 },
  splitter: { role: 'field', hp: 5, speed: 2.35, damage: 20, radius: 0.95, score: 15, splitCount: 3 },
  bossHeavy: { role: 'boss', hp: 48, speed: 1.25, damage: 52, radius: 1.95, score: 110 },
  bossAgile: { role: 'boss', hp: 36, speed: 2.95, damage: 38, radius: 1.65, score: 125, chargeSpeed: 9.7, chargeCooldown: 1.65, chargeDuration: 0.35 },
  earthTitan: { role: 'boss', hp: 440, speed: 0.12, damage: 78, radius: 4.6, score: 420 },
};

export const SAFETY_LIMITS = {
  maxSynergyReactionsPerHit: 3,
  maxSynergyEventsPerFrame: 24,
  maxKillSynergyEventsPerFrame: 12,
  maxDeathBurstTargets: 8,
  maxStatusPropagationPerEvent: 6,
  maxSynergyChainDepth: 2,
  reactionInternalCooldownFrames: 5,
  maxProjectileCount: 4096,
  maxVisualProjectilesPerShot: 10,
  maxVisualProjectilesPerShotLowQuality: 6,
  maxBulletsSpawnPerFrame: 14,
  maxActiveBullets: 180,
  maxActiveBulletsSoft: 132,
  maxChainBeams: 80,
  maxDamageNumbers: 40,
  maxEnemyStatusEffects: 90,
  maxLightningChainsPerHit: 6,
  maxLightningChainsPerFrame: 20,
  maxVfxSpawnPerFrame: 96,
  maxDotTicksPerFrame: 24,
  maxSplashDamageEventsPerFrame: 18,
  maxHitResolutionsPerFrame: 72,
  maxStatusVfxPerFrame: 28,
  maxRocketSplashTargets: 10,
  maxRocketSplashSearchCells: 16,
  maxBulletLifetime: 0.95,
  bulletSoftRange: gameplayConfig.arena.spawnMaxDistance + 14,
  bulletHardRange: gameplayConfig.arena.spawnMaxDistance + 24,
  broadphaseCellSize: 7,
  broadphaseMaxCellsPerQuery: 16,
};

export function formatDuration(totalSeconds) {
  const hours = Math.floor(totalSeconds / 3600);
  const minutes = Math.floor((totalSeconds % 3600) / 60);
  const seconds = Math.floor(totalSeconds % 60);
  if (hours > 0) return `${hours}h ${minutes}m ${seconds}s`;
  if (minutes > 0) return `${minutes}m ${seconds}s`;
  return `${seconds}s`;
}
