export function createGameState(profile, helpers) {
  return {
    running: false,
    hp: helpers.getPlayerMaxHp(),
    score: 0,
    wave: 1,
    waveInLevel: 1,
    worldIndex: profile.progression.selectedWorld,
    levelIndex: profile.progression.selectedLevel,
    spawnLeft: 0,
    fireCooldown: 0,
    wavePause: 1,
    yaw: 0,
    totalKills: 0,
    waveKills: 0,
    pickupSpawnTimer: 5,
    pickupSpawnInterval: 10,
    moveSpeedMultiplier: helpers.getBaseMoveSpeedMultiplier(),
    projectileCount: 1,
    runCredits: 0,
    damageDealt: 0,
    elapsedRunTime: 0,
    savedRunTime: 0,
    lastProfileSaveAt: 0,
    pendingResult: null,
    performance: {
      frameMs: 16.7,
      fps: 60,
      qualityLevel: 0,
      debugEnabled: false,
      activeEnemyEffects: 0,
    },
    ui: {
      activeMenuScreen: 'home',
      pickupNotices: [],
    },
    entities: {
      enemies: [],
      bullets: [],
      damageNumbers: [],
      vfxParticles: [],
      chainBeams: [],
      powerPickups: [],
    },
    runPowers: {
      stacks: {
        fire: 0,
        ice: 0,
        lightning: 0,
        poison: 0,
        rockets: 0,
        doubler: 0,
        movementSpeed: 0,
        shield: 0,
      },
      shieldHp: 0,
    },
  };
}
